dist: xenial
language: java
jdk:
  - openjdk8
script:
  - "mvn clean"
  - "mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar"
notifications:
  email:
    recipients:
      - skypencil+travis@gmail.com
addons:
  sonarcloud:
    organization: "kengotoda-github"
    token:
      secure: "cJr8pKjm834HTREIFc/Vl67YXV4gT22qugKb8Kez+V1d9fCOe2TcKnNUH+GXJsCoLOa+1mI5uYtlX/rX4KAmoK25jhI08keq5FeRPfezZw7AhLqoJuPGAjKLDLYj25B4SUPlvIR1yxhAD7ds+cowRhHDnjrKmeHVZqwZm5jzzcMWG2mWSvNArMRBy0R9kbBXTZFxV+xKhcfv1Q2x6ZnmGS1kBIELKy0l6IAWeOPX09q2OIBPHS4HK0DMk0TEIXmVysmRNtvURkrDOOvz4NmPRbUpRCR2JUGT9ANcVi8cnsCsQmboIOC0LdlwvfJICfRzubZOv0GPQtTlLjIq0076/jUug9G3mWdPhhdxNFcDmaufZx38cff15fmHytayTpAgffqbMF8FWg0uDfbHwii8RBZH9Guea/iUD8GW1L1/rW2wowJaKFbCzDBJLwN0BLd1Tb+q6WfCNHA+mub6UxIcqgukOsqxIUR0G0GaxWGu89ystgtAmaOLKktxWvYyup9I/UcXS0wIuRcOkyQ0pxxSw6WabyLV9iD4qp169mNiPH5f8WUL5WtQoHfx8+FL1/bnXcrxag3QPrNB3hmyEKo46V7nzi3HphjrzrhysxjPUqD/jTaqQUMP2WM4m9wYlkxx+v0MZ0ihNdXauf9i+sd1oM2dohJUzUxKEjjrh0GZL8c="
